name: Deploy to dev
on:
  push:
    branches:
      - "*"
      - "!master"
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/spinnsyn:${{ github.sha }}
jobs:
  build-push-deploy:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies for server
        run: |
          npm install
        working-directory: ./server
      - name: Run tests for server
        run: |
          npm run test
        working-directory: ./server
      - name: Install dependencies for client
        run: |
          npm install
        working-directory: ./client
      #- name: Run tests for client
      #  env:
      #    CI: true
      #  run: |
      #    npm run test
      #  working-directory: ./client
      - name: Build server
        run: |
          npm run compile
        working-directory: ./server
      - name: Build client
        run: |
          npm run build
        working-directory: ./client
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
      - name: Deploy app to preprod
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-sbs
          RESOURCE: naiserator-dev.yml